#THEORY

###Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?



NumPy (Numerical Python) is a fundamental library for scientific computing and data analysis in Python, offering efficient tools for handling large arrays and matrices of numerical data. Its primary purpose is to provide a high-performance, flexible, and comprehensive framework for numerical calculations, which enhances Python’s capabilities in several ways. Here's a breakdown of why NumPy is so valuable and how it benefits scientific computing and data analysis:

1. Efficient Data Structures (ndarray)
Purpose: The core structure in NumPy is the ndarray (N-dimensional array), which can represent arrays of any dimension, like vectors, matrices, or higher-dimensional arrays.
Advantages: Compared to Python's native lists, ndarray objects are more compact and allow for faster operations. This is because they store data in contiguous memory blocks, facilitating faster access and manipulation.
2. Vectorized Operations and Broadcasting
Purpose: NumPy enables element-wise operations on arrays without requiring explicit loops.
Advantages: Vectorized operations are both easier to write and significantly faster than traditional loops in Python. Broadcasting (automatic alignment of arrays of different shapes) allows for complex calculations on arrays of different shapes without manual replication, improving both performance and readability.
3. Speed and Performance through C Integration
Purpose: NumPy is written in C and uses highly optimized C libraries to perform numerical operations.
Advantages: This makes it much faster for numerical computations than native Python. Operations that would take seconds or minutes in Python loops can be done in milliseconds with NumPy, especially when dealing with large datasets.
4. Comprehensive Mathematical Functions
Purpose: NumPy provides a vast array of built-in functions for mathematical operations (e.g., trigonometry, linear algebra, random number generation).
Advantages: This comprehensive set of tools enables users to perform a wide range of scientific computations directly within NumPy, often replacing the need for other specialized software.
5. Support for Multidimensional Data and Linear Algebra
Purpose: Scientific computing often requires operations on matrices and higher-dimensional data.
Advantages: NumPy has built-in functions for matrix operations (like dot products, cross products, and matrix decompositions) and other linear algebraic computations. This makes it ideal for data manipulation in fields like machine learning, physics, and engineering.
6. Integration with Other Libraries
Purpose: NumPy serves as the foundation for many other Python libraries, including pandas, SciPy, and TensorFlow.
Advantages: Its compatibility and interoperability with these libraries make NumPy essential for data analysis and machine learning workflows, enabling complex data manipulations and model-building tasks with ease.
7. Memory Efficiency and Scalability
Purpose: In scientific computing and data analysis, memory usage is critical, especially with large datasets.
Advantages: NumPy’s efficient memory usage enables the handling of larger datasets than would be feasible with native Python lists, improving scalability in data-intensive applications.
8. Data Analysis and Cleaning
Purpose: NumPy facilitates fast and efficient data analysis and preprocessing steps.
Advantages: It provides convenient ways to filter, slice, and transform data, making it indispensable for tasks in data cleaning and preprocessing, essential steps in any data analysis pipeline.

###Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other

In NumPy, both np.mean() and np.average() functions compute the average of array elements, but they have some key differences, especially in their handling of weights. Here’s a detailed comparison:

np.mean()
Purpose: Computes the arithmetic mean (average) of array elements.
Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=False)
Behavior: This function calculates the mean by summing all the elements along the specified axis and dividing by the number of elements. It treats all elements equally and does not allow for weighting.
Use Case: Use np.mean() when you want a simple, unweighted average of the elements in an array.

np.average()
Purpose: Computes the weighted average of array elements.
Syntax: np.average(array, axis=None, weights=None, returned=False)
Behavior: This function has an additional weights parameter, allowing for a weighted mean. If weights are provided, each element in the array is multiplied by the corresponding weight, and the sum of the weighted elements is divided by the sum of the weights.
Use Case: Use np.average() when you need a weighted average, where different elements in the array contribute unequally to the final average.

When to Use Each:

Use np.mean() when you need a simple, straightforward average without considering any weights.
Use np.average() if you need a weighted average, allowing specific elements to contribute more to the final mean.

###Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In NumPy, you can reverse arrays along different axes using slicing, as well as specialized functions like np.flip(). Here’s how you can reverse arrays in both 1D and 2D contexts:

1. Reversing a 1D Array
For a 1-dimensional array, reversing simply means reversing the order of elements.
Method 1: Using Slicing

In [1]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = array_1d[::-1]
print(reversed_1d)


[5 4 3 2 1]


In [2]:
#method 2 : Using np.flip()

reversed_1d_flip = np.flip(array_1d)
print(reversed_1d_flip)


[5 4 3 2 1]


Reversing a 2D Array Along Different Axes:

For a 2-dimensional array (matrix), you can reverse along the rows (axis=0), the columns (axis=1), or both.

In [3]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


In [4]:
#flip alomg rows (axis=0)
flipped_rows = np.flip(array_2d, axis=0)
print(flipped_rows)



[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [5]:
#flip alomg columns (axis=1)
flipped_columns = np.flip(array_2d, axis=1)
print(flipped_columns)



[[3 2 1]
 [6 5 4]
 [9 8 7]]


###How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In NumPy, you can determine the data type of elements in an array using the dtype attribute. This is important in scientific computing and data analysis, as choosing the appropriate data type directly impacts memory usage and computational performance.

How to Determine the Data Type
To check the data type of elements in a NumPy array, use the .dtype attribute.

Example:

In [6]:
import numpy as np

array = np.array([1, 2, 3])
print(array.dtype)


int64


Importance of Data Types in Memory Management and Performance
Data types in NumPy define how many bytes each element in an array will occupy, and they directly affect the efficiency and speed of computations. Here’s why data types are critical for memory management and performance:

Memory Efficiency:

Each data type (int32, float64, etc.) specifies the number of bytes required to store each element.
For example, int8 uses 1 byte per element, while int64 uses 8 bytes per element. By selecting the smallest data type that can accommodate your values, you reduce memory usage.
For large datasets, using lower-precision types can drastically reduce memory consumption.

Performance Optimization:

Lower-precision data types allow NumPy to perform computations faster because smaller data types require less data transfer and can be processed more quickly by the CPU and GPU.
For instance, calculations with float32 arrays will generally be faster than with float64 arrays, especially when working on large arrays or when using parallel processing (e.g., on GPUs).
Type-Specific Operations:

Some algorithms are optimized for certain data types. For example, machine learning models often use float32 or int32 to balance memory usage and speed.
In some cases, however, using lower precision can lead to accuracy issues in calculations, especially in cases involving very small or very large values (where float64 might be preferable).
Preventing Data Type Overflows:

If the values in an array exceed the range of the chosen data type, this can lead to overflow errors, resulting in incorrect values. For example, int8 ranges from -128 to 127, so any value outside this range will cause an overflow.
Choosing an appropriate data type can prevent these issues and ensure data integrity.

###Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In NumPy, an ndarray (N-dimensional array) is a powerful, versatile array structure that allows for efficient storage, manipulation, and computation of large datasets in Python. ndarrays form the backbone of scientific computing in Python due to their performance advantages over standard Python lists, especially for numerical data.

Key Features of ndarrays
Multidimensional Structure:

ndarrays can have any number of dimensions, from 1D arrays (similar to lists) to higher-dimensional arrays like 2D matrices and beyond.
This flexibility allows them to represent vectors, matrices, and even tensors easily.
Homogeneous Data Type:

All elements in an ndarray must have the same data type (e.g., all integers, all floats). This uniformity improves memory efficiency and speeds up computation.
The data type of an array can be checked using the .dtype attribute.
Fixed Size:

Once created, the size of an ndarray cannot be changed. While elements within the array can be modified, the number of elements remains constant.
This immutability of size also contributes to memory efficiency, as contiguous memory blocks are allocated for arrays.
Efficient Memory Management:

ndarrays store data in contiguous memory blocks, unlike Python lists, which are pointers to separate memory locations.
This contiguous storage allows for faster access and manipulation and enables the use of vectorized operations.
Support for Mathematical Operations and Broadcasting:

ndarrays allow for vectorized operations (element-wise operations), enabling fast and efficient calculations without the need for loops.
Broadcasting is another powerful feature that enables operations on arrays of different shapes by "stretching" smaller arrays to match larger ones, where possible, saving both time and code complexity.
Rich Functionality:

NumPy provides a large number of functions to manipulate ndarrays, including slicing, reshaping, mathematical functions, statistical operations, and linear algebra.
These built-in functions are optimized for ndarray operations, providing both speed and convenience.

Differences Between ndarrays and Standard Python Lists

ExAMPLE :

In [7]:
python_list = [1, 2, 3, 4]
python_list_squared = [x * x for x in python_list]  # List comprehension for element-wise operations


In [8]:
import numpy as np

ndarray = np.array([1, 2, 3, 4])
ndarray_squared = ndarray ** 2  # Vectorized operation (faster and more concise)


### Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

NumPy arrays (ndarrays) offer significant performance benefits over Python lists for large-scale numerical operations due to their efficient memory handling, vectorized operations, and support for lower-level optimizations. Here’s a deeper look at why NumPy arrays outperform Python lists in these contexts:

1. Memory Efficiency and Data Contiguity
Fixed, Homogeneous Data Type: In NumPy arrays, all elements have the same data type, which allows the data to be stored in a contiguous block of memory. This eliminates the need for individual pointers (as in Python lists), reducing memory overhead and improving cache utilization.
Contiguous Memory Blocks: Because data is stored contiguously, the CPU can quickly access neighboring elements, making array operations faster, especially for large datasets. This contiguous storage also enables NumPy to leverage efficient lower-level implementations.

2. Vectorized Operations
No Explicit Loops: NumPy allows element-wise operations on arrays (e.g., addition, multiplication) without the need for explicit Python loops, thanks to its vectorized operations. These vectorized operations are highly optimized and implemented in C, enabling faster execution than Python's for-loops.
Efficient SIMD Processing: Vectorized operations allow NumPy to use Single Instruction, Multiple Data (SIMD) processing, where a single operation can be applied to multiple data points simultaneously. This is especially beneficial for large-scale computations.

3. Broadcasting
Automatic Alignment of Array Shapes: Broadcasting allows operations between arrays of different shapes without requiring explicit looping or manual alignment, as NumPy automatically expands the smaller array to match the dimensions of the larger one.
Elimination of Explicit Looping for Dimensionality Matching: This enables faster execution for operations involving arrays of different shapes, which would otherwise require multiple nested loops in pure Python.

4. Low-Level Optimization and BLAS/LAPACK Integration
Compiled with C and Fortran: Many of NumPy's operations are implemented in lower-level languages like C and Fortran, making them much faster than Python's high-level interpreted code.
Integration with BLAS and LAPACK Libraries: NumPy uses highly optimized linear algebra libraries like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra PACKage) for complex operations (e.g., matrix multiplications, inversions, and decompositions), which are significantly faster than Python’s list-based implementations.

5. Reduced Overhead from Python Function Calls
Avoiding Repeated Python Function Calls: In numerical computations with Python lists, operations often involve repeatedly calling functions within loops, which adds considerable overhead in an interpreted language like Python.
Internal Loops in Compiled Code: NumPy minimizes this overhead by executing loops internally in C or Fortran, reducing function call overhead and improving execution speed.

###Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output

In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. They are helpful for combining multiple arrays along specific axes, which can be particularly useful when you need to manipulate data structures like matrices or higher-dimensional arrays.

1. np.vstack()
Purpose: Vertically stacks arrays on top of each other, creating a new array.
Requirement: The input arrays must have the same number of columns (i.e., the same second dimension for 2D arrays).
Result: A single array where the input arrays are placed one on top of the other.

2. np.hstack()
Purpose: Horizontally stacks arrays side by side, creating a new array.
Requirement: The input arrays must have the same number of rows (i.e., the same first dimension for 2D arrays).
Result: A single array where the input arrays are placed side by side.


In [9]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Using vstack to combine array1 and array2
result_vstack = np.vstack((array1, array2))
print(result_vstack)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
# Using the same arrays as before
result_hstack = np.hstack((array1, array2))
print(result_hstack)


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In NumPy, np.fliplr() and np.flipud() are functions used to flip arrays in different directions. Here’s a breakdown of each function and how they affect the array:

1. np.fliplr()
Purpose: Flips (reverses) the elements in each row, effectively flipping the array along the vertical axis (left-to-right).
Applies to: Only works on arrays with two or more dimensions (i.e., 2D arrays or higher).
Effect: It reverses the order of columns in the array but keeps the rows in their original order.

In [11]:
import numpy as np

# Creating a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Using fliplr
fliplr_result = np.fliplr(array)
print(fliplr_result)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. np.flipud()
Purpose: Flips (reverses) the elements in each column, effectively flipping the array along the horizontal axis (top-to-bottom).
Applies to: Works on arrays with any number of dimensions (1D, 2D, or higher).
Effect: It reverses the order of rows in the array but keeps the columns in their original order.

In [12]:
# Using flipud
flipud_result = np.flipud(array)
print(flipud_result)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The np.array_split() function in NumPy is used to split an array into a specified number of smaller sub-arrays. It is similar to np.split(), but with an important difference: array_split() can handle cases where the array cannot be divided evenly, while split() cannot.

Key Features of array_split()
Flexible Splitting: array_split() allows for splitting an array into a specified number of parts, even if the array's length is not perfectly divisible by that number.
Handling Uneven Splits: When the array length doesn’t evenly divide by the number of splits, array_split() distributes the elements as evenly as possible, assigning extra elements to the earlier sub-arrays.
How array_split() Handles Uneven Splits
When the array length isn’t an exact multiple of the number of splits, array_split() divides the array into parts that are as close to equal as possible. Any remaining elements (the "remainder") are added one at a time to the beginning sub-arrays until all elements are distributed.

For example, if you try to split an array of length 10 into 3 parts, array_split() will create sub-arrays of lengths 4, 3, and 3, respectively, instead of failing or truncating data.

In [13]:
import numpy as np

# Creating a 1D array of length 10
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Splitting the array into 3 parts
result = np.array_split(array, 3)
print(result)


[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


Splitting Multi-Dimensional Arrays
The array_split() function can also split multi-dimensional arrays along a specified axis. This allows for splitting along rows (axis=0) or columns (axis=1) in 2D arrays.

In [14]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Splitting the 2D array into 2 parts along the columns (axis=1)
result_2d = np.array_split(array_2d, 2, axis=1)
print(result_2d)


[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


###. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In NumPy, vectorization and broadcasting are two core concepts that enable efficient array operations by eliminating explicit loops and optimizing memory usage. They allow operations on arrays to be executed faster and more concisely, especially for large datasets.

1. Vectorization
Definition: Vectorization is the process of applying operations to entire arrays or large chunks of data at once, without the need for explicit Python loops.

How it Works: In NumPy, vectorized operations leverage low-level implementations in languages like C or Fortran, which process multiple elements simultaneously. This allows operations to be applied directly on arrays, making them significantly faster than looping over individual elements in Python.

Advantages of Vectorization:

Speed: By avoiding Python loops and leveraging optimized low-level code, vectorized operations are much faster.
Simplicity: Vectorized syntax is concise, making the code easier to read and maintain.
Memory Efficiency: Processes multiple elements at once without creating intermediate variables, reducing memory overhead.

2. Broadcasting
Definition: Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically "stretching" or expanding the smaller array to match the shape of the larger array.

How it Works: When two arrays have compatible shapes (based on broadcasting rules), NumPy expands the dimensions of the smaller array along the axis of the larger one so they can be combined element-wise. Broadcasting is only possible when the dimensions of the arrays align in a compatible way.

Broadcasting Rules:

If arrays have different shapes, NumPy starts from the last dimension and works backwards.
Two dimensions are compatible if they are equal or if one of them is 1.

Advantages of Broadcasting:

Avoids Explicit Looping: Broadcasting eliminates the need for nested loops to match dimensions manually, making code more efficient.
Reduces Memory Usage: Instead of creating a larger array explicitly, broadcasting uses temporary views of the original arrays, which saves memory.
Simplifies Code: Broadcasting syntax is clean and expressive, reducing code complexity in multi-dimensional operations.

#PRACTICAL

###1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [15]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Display the original array
print("Original Array:")
print(array_3x3)

# Interchange its rows and columns (transpose the array)
interchanged_array = array_3x3.T

# Display the transposed array
print("\nInterchanged Rows and Columns (Transposed Array):")
print(interchanged_array)


Original Array:
[[25 78 38]
 [74 60 92]
 [67 18 58]]

Interchanged Rows and Columns (Transposed Array):
[[25 74 67]
 [78 60 18]
 [38 92 58]]


###Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [16]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements from 0 to 9

# Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape the array into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print results
print("1D Array:", array_1d)
print("2x5 Array:\n", array_2x5)
print("5x2 Array:\n", array_5x2)


1D Array: [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


###Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array



In [17]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print results
print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.67165557 0.59410853 0.3736359  0.54092924]
 [0.47439197 0.19652077 0.60664358 0.19294746]
 [0.05485722 0.87171274 0.53275262 0.94926146]
 [0.68151513 0.95229769 0.53036908 0.8332544 ]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.67165557 0.59410853 0.3736359  0.54092924 0.        ]
 [0.         0.47439197 0.19652077 0.60664358 0.19294746 0.        ]
 [0.         0.05485722 0.87171274 0.53275262 0.94926146 0.        ]
 [0.         0.68151513 0.95229769 0.53036908 0.8332544  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [18]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

# Print the result
print(array_integers)


[10 15 20 25 30 35 40 45 50 55 60]


###Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [19]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)   # Convert to uppercase
lowercase_array = np.char.lower(string_array)   # Convert to lowercase
titlecase_array = np.char.title(string_array)    # Convert to title case

# Print the results
print("Original Array:")
print(string_array)
print("\nUppercase Array:")
print(uppercase_array)
print("\nLowercase Array:")
print(lowercase_array)
print("\nTitlecase Array:")
print(titlecase_array)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']


###Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [20]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word in the array
spaced_words_array = np.array([' '.join(word) for word in words_array])

# Print the result
print("Original Array:")
print(words_array)
print("\nArray with Spaces Between Characters:")
print(spaced_words_array)


Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


###

In [25]:
import numpy as np

# Create two 2D NumPy arrays
array_a = np.array([[1, 2, 3],
                     [4, 5, 6]])
array_b = np.array([[10, 20, 30],
                     [40, 50, 60]])

# Perform element-wise addition
sum = array_a + array_b

# Perform element-wise subtraction
subtraction = array_a - array_b

# Perform element-wise multiplication
multiplication = array_a * array_b

# Perform element-wise division
division = array_a / array_b

print(sum)

print(subtraction)

print(multiplication)

print(division)



[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]]


### Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [26]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


### Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [27]:
import numpy as np

# Create an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers:")
print(random_integers)
print("\nPrime Numbers:")
print(prime_numbers)


Random Integers:
[361 597 173 881 816 674 741 341 268  11 920 358 776 917 497 111 825 236
 145 734 540 266 724 214 691  95  69 477  24 506 434 899 819 547 422  96
 180 950 833   9 219 222 780 346 991 505 345 436 555 590 296 955 471 420
 469 482 593 142 515 986 355 217  73 217 332 503 687 398  36  20 685 241
 793 361  38 443 108 171  85 807 982 708 209 780 485 990 585 914  31 399
   9 823 584 450 384 898 620 954 759 312]

Prime Numbers:
[173, 881, 11, 691, 547, 991, 593, 73, 503, 241, 443, 31, 823]


### Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [36]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Using fixed values for clarity (e.g., temperature in degrees Celsius)
daily_temperatures = np.array([
    22, 24, 25, 23, 20, 21, 24,  # Week 1
    26, 27, 28, 29, 30, 28, 25,  # Week 2
    22, 21, 20, 19, 22, 23, 25,  # Week 3
    27, 26, 25, 24, 23, 22, 21,  # Week 4
    20, 19, 18, 17,              # Last 2 days
])

# Calculate weekly averages
# Reshape into a 4-week structure (4 weeks of 7 days, and remaining days can be handled separately)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)  # First 28 days for 4 full weeks
remaining_days = daily_temperatures[28:]  # Last 2 days

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the results
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)

# Handle the last week with remaining days
last_week_average = np.mean(remaining_days) if len(remaining_days) > 0 else None
print("\nAverage of Remaining Days:")
print(last_week_average)



Daily Temperatures for the Month:
[22 24 25 23 20 21 24 26 27 28 29 30 28 25 22 21 20 19 22 23 25 27 26 25
 24 23 22 21 20 19 18 17]

Weekly Averages:
[22.71428571 27.57142857 21.71428571 24.        ]

Average of Remaining Days:
18.5
